//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleEventSubscriber.VelibServiceSubReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelibServiceSubReference.IVelibServiceSub", CallbackContract=typeof(ConsoleEventSubscriber.VelibServiceSubReference.IVelibServiceSubCallback))]
    public interface IVelibServiceSub {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibServiceSub/SubscribeBikesNumber", ReplyAction="http://tempuri.org/IVelibServiceSub/SubscribeBikesNumberResponse")]
        void SubscribeBikesNumber(string stationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibServiceSub/SubscribeBikesNumber", ReplyAction="http://tempuri.org/IVelibServiceSub/SubscribeBikesNumberResponse")]
        System.Threading.Tasks.Task SubscribeBikesNumberAsync(string stationName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibServiceSubCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVelibServiceSub/StationBikesNumberChanged")]
        void StationBikesNumberChanged(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibServiceSubChannel : ConsoleEventSubscriber.VelibServiceSubReference.IVelibServiceSub, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibServiceSubClient : System.ServiceModel.DuplexClientBase<ConsoleEventSubscriber.VelibServiceSubReference.IVelibServiceSub>, ConsoleEventSubscriber.VelibServiceSubReference.IVelibServiceSub {
        
        public VelibServiceSubClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public VelibServiceSubClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public VelibServiceSubClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceSubClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceSubClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SubscribeBikesNumber(string stationName) {
            base.Channel.SubscribeBikesNumber(stationName);
        }
        
        public System.Threading.Tasks.Task SubscribeBikesNumberAsync(string stationName) {
            return base.Channel.SubscribeBikesNumberAsync(stationName);
        }
    }
}
